runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /static
    static_dir: static_dir
    application_readable: true
  - url: /.*
    script: app.app

libraries:
  - name: ssl
    version: latest
